[package]
name = "riscv-emulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
goblin = "0.6.1"
termion = "2.0.1"
tui = { version = "0.17.0", features = ["termion"] }
